config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 7 CRUD ACTIONS
  # index, all, new, create, edit, update, destroy
  # I.1 READ all
  get '/tasks', to: 'tasks#index'
  # # II. CREATE - 1. get, 2. post
  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create', as: 'task_create'
  # I.2 READ specific
  get '/tasks/:id', to: 'tasks#show', as: 'task'
  # # III. UPDATE
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'
  patch '/tasks/:id', to: 'tasks#update', as: 'task_update'
  # # IV. DELETE
  delete '/tasks/:id', to: 'tasks#destroy', as: 'task_destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action
  # 7 CRUD ACTIONS
  # index, show, new, create, edit, update, destroy
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.check_box :completed %>
  <%= t.submit %>
<% end %>

<p><%= link_to "Back to all tasks", tasks_path %></p>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
     <li>
      <%= task.completed %>
      <%= link_to task.title, task_path(task) %>
    </li>
  <% end %>
</ul>
<hr>
<p><%= link_to "+ create new task", tasks_new_path %></p>

app/views/tasks/new.html.erb
<h1>Create new task</h1>
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.check_box :completed %>
  <%= t.submit %>
<% end %>

<p><%= link_to "Back to all tasks", tasks_path %></p>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= link_to "Edit this task", task_edit_path(@task)%></p>
<p style="background-color: #ddd"><%= @task.details %></p>
<p>this task is completed?: <%= @task.completed %></p>
<hr>
<p><%= link_to "Delete this task",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
</p>
<hr>
<p><%= link_to "Back to all tasks", tasks_path %></p>